// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVjpF_29iIRPUfx_cAE8JksoQ1vEWVu6Y',
    appId: '1:131989069516:web:ab9a81fba0e47856276c69',
    messagingSenderId: '131989069516',
    projectId: 'somjeeb-4fc1b',
    authDomain: 'somjeeb-4fc1b.firebaseapp.com',
    storageBucket: 'somjeeb-4fc1b.appspot.com',
    measurementId: 'G-XN400K9682',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCniUmNFVBz-vrRS8w2_-KLuI_fGu2X3z8',
    appId: '1:131989069516:android:083104af1a051570276c69',
    messagingSenderId: '131989069516',
    projectId: 'somjeeb-4fc1b',
    storageBucket: 'somjeeb-4fc1b.appspot.com',
  );
}
